{% set name = "ompl" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ompl/ompl/archive/{{ version }}.tar.gz
  sha256: db1665dd2163697437ef155668fdde6101109e064a2d1a04148e45b3747d5f98

build:
  number: 3
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - boost-cpp
    - eigen
    - flann
    - libode
  run:
    - boost-cpp

test:
  commands:
    - test -f $PREFIX/lib/libompl${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/pkgconfig/ompl.pc  # [unix]
    - test -f $PREFIX/share/ompl/cmake/omplConfig.cmake  # [unix]
    - test -f $PREFIX/include/ompl-1.5/ompl/geometric/planners/rrt/RRT.h  # [unix]
    - if not exist %LIBRARY_LIB%\\ompl.lib exit 1  # [win]

about:
  home: https://ompl.kavrakilab.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The Open Motion Planning Library (OMPL)'
  description: |
    The Open Motion Planning Library (OMPL) consists of a set of sampling-based motion planning algorithms. The content
    of the library is limited to these algorithms, which means there is no
    environment specification, no collision detection or visualization. The
    library is designed so it can be easily integrated into systems that provide
    the additional needed components. For examples of complete systems using
    OMPL, see OMPL.app and MoveIt!. We have also developed a educational module
    on motion planning that is centered around OMPL.app. We are looking for
    educational partners to use and further develop the material. Please contact
    us for more information.

  dev_url: https://github.com/ompl/ompl
  doc_url: https://ompl.kavrakilab.org/

extra:
  recipe-maintainers:
    - wolfv
    - seanyen
