context:
  name: ompl
  version: "2.0.2"
  major_version: 2
  minor_version: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ompl/ompl/archive/${{ version }}.tar.gz
  sha256: d867190a46a7f730923475a68af2e09fc9e796017a59be395a4bf3900d0c3ae4
  patches:
    - use-system-nanobind.patch
    - 1467.patch

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - if: build_platform!=target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - libboost-devel
    - eigen
    - eigen-abi-devel
    - flann
    - libode
    - python
    - numpy
    - nanobind
    - typing-extensions
  run:
    - python
    # Required by find_package(ompl)
    - libboost-devel
    - eigen

  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}


tests:
  - python:
      imports:
        - ompl
        - ompl.base
        - ompl.control
        - ompl.geometric
        - ompl.tools
        - ompl.util

  - package_contents:
      include:
        - ompl-${{ major_version }}.${{ minor_version }}/ompl/geometric/planners/rrt/RRT.h
      lib:
        - ompl

  - script:
      - cmake-package-check ompl --targets ompl::ompl
      - if: not win
        then:
          - test -f "${PREFIX}/lib/pkgconfig/ompl.pc"
    requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}

about:
  homepage: https://ompl.kavrakilab.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The Open Motion Planning Library (OMPL)'
  description: |
    The Open Motion Planning Library (OMPL) consists of a set of sampling-based motion planning algorithms. The content
    of the library is limited to these algorithms, which means there is no
    environment specification, no collision detection or visualization. The
    library is designed so it can be easily integrated into systems that provide
    the additional needed components. For examples of complete systems using
    OMPL, see OMPL.app and MoveIt!. We have also developed a educational module
    on motion planning that is centered around OMPL.app. We are looking for
    educational partners to use and further develop the material. Please contact
    us for more information.

  repository: https://github.com/ompl/ompl
  documentation: https://ompl.kavrakilab.org/

extra:
  recipe-maintainers:
    - traversaro
    - wolfv
    - seanyen
