context:
  name: ompl
  version: "2.0.1"
  major_version: 2
  minor_version: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ompl/ompl/archive/${{ version }}.tar.gz
  sha256: 365f052d5fb4419ed016394ddb26ab83dee6514b90565ad30af044a09b122aef

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - if: build_platform!=target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
  host:
    - libboost-devel
    - eigen
    - flann
    - libode
    - python
    - numpy
  run:
    - python
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}


tests:
  - script:
      - if: unix
        then:
          - test -f "${PREFIX}/lib/libompl${{ SHLIB_EXT }}"
          - test -f "${PREFIX}/lib/pkgconfig/ompl.pc"
          - test -f "${PREFIX}/share/ompl/cmake/omplConfig.cmake"
          - test -f "${PREFIX}/include/ompl-${{ major_version }}.${{ minor_version }}/ompl/geometric/planners/rrt/RRT.h"
      - if: win
        then:
          - if not exist %LIBRARY_LIB%\ompl.lib exit 1

about:
  homepage: https://ompl.kavrakilab.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The Open Motion Planning Library (OMPL)'
  description: |
    The Open Motion Planning Library (OMPL) consists of a set of sampling-based motion planning algorithms. The content
    of the library is limited to these algorithms, which means there is no
    environment specification, no collision detection or visualization. The
    library is designed so it can be easily integrated into systems that provide
    the additional needed components. For examples of complete systems using
    OMPL, see OMPL.app and MoveIt!. We have also developed a educational module
    on motion planning that is centered around OMPL.app. We are looking for
    educational partners to use and further develop the material. Please contact
    us for more information.

  repository: https://github.com/ompl/ompl
  documentation: https://ompl.kavrakilab.org/

extra:
  recipe-maintainers:
    - traversaro
    - wolfv
    - seanyen
